### PR TITLE
Add option to tolerate the use of the 'in' operator.

### PR DESCRIPTION
**Pull request by Xotic750**
Consider the following code:
```javascript
(function () {
    'use strict';
    /*jslint devel: true */
    /*globals Array, Object */
    /*properties
        '0', '1', '2', '3', '4', '6', '7', call, create, forEach, hasOwnProperty,
        length, log, prototype
    */

    var arrayLike = {
            0: 'a',
            1: 'b',
            2: null,
            3: 'd',
            4: undefined,
            6: 'f',
            7: NaN,
            length: 8
        },
        anArrayLike = Object.create(arrayLike, {}),
        length = anArrayLike.length,
        index,
        item;

    console.log('Using Array.prototype.forEach');
    // Correct: output matches the expected input
    Array.prototype.forEach.call(anArrayLike, function (item, index) {
        console.log('forEach', index, item);
    });

    console.log('\nIterate based on length, no filter');
    // Incorrect: outputs everything, even 'holes'
    for (index = 0; index < length; index += 1) {
        item = anArrayLike[index];
        console.log('length', index, item);
    }

    console.log('\nIterate based on length, hasOwnProperty filter');
    // Incorrect: nothing logged
    for (index = 0; index < length; index += 1) {
        if (anArrayLike.hasOwnProperty(index)) {
            item = anArrayLike[index];
            console.log('hasOwnProperty', index, item);
        }
    }

    console.log('\nIterate based on length, filter based on comparison with undefined');
    // Incorrect: everything output except index 4 and the 'hole' at index 5
    for (index = 0; index < length; index += 1) {
        item = anArrayLike[index];
        if (item !== undefined) {
            console.log('undefined', index, item);
        }
    }

    console.log('\nIterate based on length, in filter');
    // Correct: output matches the expected input, but fails jslint because of 'in'
    for (index = 0; index < length; index += 1) {
        if (index in anArrayLike) {
            item = anArrayLike[index];
            console.log('in', item);
        }
    }
}());
```
http://jsfiddle.net/Xotic750/rLj4e1a7/

```
Using Array.prototype.forEach
forEach 0 a
forEach 1 b
forEach 2 null
forEach 3 d
forEach 4 undefined
forEach 6 f
forEach 7 NaN

Iterate based on length, no filter
length 0 a
length 1 b
length 2 null
length 3 d
length 4 undefined
length 5 undefined
length 6 f
length 7 NaN

Iterate based on length, hasOwnProperty filter

Iterate based on length, filter based on comparison with undefined
undefined 0 a
undefined 1 b
undefined 2 null
undefined 3 d
undefined 6 f
undefined 7 NaN

Iterate based on length, in filter
in 0 a
in 1 b
in 2 null
in 3 d
in 4 undefined
in 6 f
in 7 NaN
```

Nothing too odd about that code, but it doesn't pass JSLint.
>Unexpected 'in'. Compare with undefined, or use the hasOwnProperty method instead.
>        if (index in anArrayLike) { 

You can see that the suggestions do not produce the same expected result, on by using `in` are the results correct.

I can't see any reason for this warning, `in` seems very clear in it's purpose? How else can you get the expected result?

That's pretty annoying when all points to it being the correct solution, other than using the ES5 `Array#forEach`. 

My projects use the `'for' with 'in' filtering` in numerous places, but will not pass JSLint and my IDE throws up the warnings. 

comparing the `in` method with the `Array#forEach` it appears faster too, as it has a little less work to do. So I can get a little more performance by tailoring my code in this way.

http://jsperf.com/jslint-in-warning

I'd like to suggest an option:

`/*jslint in: true */`

Thanks.

### CODE REVIEW

**Comment by Xotic750** [comment]
Forked incorrectly

**Comment by jacksonrayhamilton** [comment]
I recommend using `Array.prototype.forEach` in this particular case.

`in` does a deep dredge through the prototype, which can lead to unexpected results. This operator is sometimes dangerous, and because there are better alternatives, JSLint prefers those instead.

When you need to check if something is an own property, call `Object.prototype.hasOwnProperty` directly. It is the safest route to go, because if your object happens to have a property called `hasOwnProperty`, the code may fail, or the results may not be what you expect.

```js
var hasOwnProperty = Object.prototype.hasOwnProperty;
if (hasOwnProperty.call(anArrayLike, index)) {
    // ...
}
```

**Comment by Xotic750** [comment]
Please try the methods that you have advised, I provided examples and you can see that JSLint's advice is not suitable in this case, this is not the one and only case.

I added your solution to the jsFiddle and you will see that it does not work.

http://jsfiddle.net/Xotic750/6q1kyw3o/

In ES3 there is no `Array#forEach` and to shim it correctly requires the use of `in`.

**Comment by jacksonrayhamilton** [comment]
Oh I see, you're doing `anArrayLike = Object.create(arrayLike, {})`.

Don't do that. Prototypes are another feature which are troublesome and shouldn't (and needn't) be used. If you use prototypes then you can't reliably perform a `hasOwnProperty` check.

You can instead use parasitic inheritance (described [here](http://www.crockford.com/javascript/inheritance.html)) or better yet [murphy.js](https://github.com/jacksonrayhamilton/murphy).

**Comment by Xotic750** [comment]
That was just an example of how the warning message is misleading regarding `hasOwnProperty` and it is clear that comparing with `undefined` is also misleading. So you would have JSLint throw warnings against ES5 `Object.create` too? Let's now move to ES3 where to have a generic prototype method, `Array#forEach` the use of `in` is a very simple way to match the specification when creating a shim. But no, we must not use `in` because it can be dangerous (when?) or because it's expensive and could lead to unexpected results (again when? I have yet to come across any). So to do something similar to `in` (which I feel quite happy to use, is well specified in it's task and has been around since the stone age) the following code would be needed.

```javascript
(function () {
    'use strict';
    /*jslint devel: true */
    /*globals Object, TypeError */
    /*properties
        call, constructor, hasOwnProperty, length, log, prototype
    */

    /**
     * Returns true if the operand inputArg is a primitive object.
     *
     * @function isPrimitive
     * @param {*} inputArg
     * @return {boolean}
     * @see http://www.ecma-international.org/ecma-262/5.1/#sec-4.3.2
     */
    function isPrimitive(inputArg) {
        var type = typeof inputArg;

        return type === 'undefined' ||
            inputArg === null ||
            type === 'boolean' ||
            type === 'string' ||
            type === 'number';
    }

    /**
     * Throws a TypeError if the operand inputArg is not an object or not a function,
     * otherise returns the object.
     *
     * @function throwIfIsPrimitive
     * @param {*} inputArg
     * @throws {TypeError} If inputArg is not an object or a function.
     * @return {(Object|Function)}
     */
    function throwIfIsPrimitive(inputArg) {
        if (isPrimitive(inputArg)) {
            throw new TypeError('called on non-object: ' + typeof inputArg);
        }

        return inputArg;
    }

    /**
     * Returns true if the operand inputArg is not a primitive object.
     *
     * @function isNotPrimitive
     * @param {*} inputArg
     * @return {boolean}
     * @see http://www.ecma-international.org/ecma-262/5.1/#sec-4.3.2
     */
    function isNotPrimitive(inputArg) {
        return !isPrimitive(inputArg);
    }

    /**
     * @function inPrototype
     * @param {Object} inputArg The object to be tested.
     * @param {string} property The property name.
     * @return {boolean} True if the property is in the object's prototype, otherwise false.
     */
    function inPrototype(inputArg, property) {
        throwIfIsPrimitive(inputArg);

        return isNotPrimitive(inputArg.constructor) &&
            isNotPrimitive(inputArg.constructor.prototype) &&
            Object.prototype.hasOwnProperty.call(inputArg.constructor.prototype, property);
    }

    /**
     * @function inObject
     * @param {*} inputArg The object to be tested.
     * @param {string} property The property name.
     * @return {boolean} True if the property is on the object or in the object's prototype, otherwise false.
     */
    function inObject(inputArg, property) {
        throwIfIsPrimitive(inputArg);

        return Object.prototype.hasOwnProperty.call(inputArg, property) || inPrototype(inputArg, property);
    }

    function Ctr() {
        this[0] = 'a';
        this[2] = null;
        this[3] = 'd';
        this[4] = undefined;
        this[6] = 'f';
        this[7] = NaN;
        this.length = 8;
    }

    Ctr.prototype[1] = 'b';

    var arrayLike = new Ctr(),
        length = arrayLike.length,
        index,
        item;

    console.log('\nIterate based on length, no filter');
    // Incorrect: outputs everything, even 'holes'
    for (index = 0; index < length; index += 1) {
        item = arrayLike[index];
        console.log('length', index, item);
    }

    console.log('\nIterate based on length, hasOwnProperty filter');
    // Incorrect: this is not the same as ES5 'Array#forEach'
    for (index = 0; index < length; index += 1) {
        if (arrayLike.hasOwnProperty(index)) {
            item = arrayLike[index];
            console.log('hasOwnProperty', index, item);
        }
    }

    console.log('\nIterate based on length, filter based on comparison with undefined');
    // Incorrect: everything output except index 4 and the 'hole' at index 5
    for (index = 0; index < length; index += 1) {
        item = arrayLike[index];
        if (item !== undefined) {
            console.log('undefined', index, item);
        }
    }

    console.log('\nIterate based on length, in filter');
    // Correct: output matches the expected input, but fails jslint because of 'in'
    for (index = 0; index < length; index += 1) {
        if (index in arrayLike) {
            item = arrayLike[index];
            console.log('in', index, item);
        }
    }

    console.log('\nIterate based on length, inObject crafted filter');
    // Correct: output matches the expected input and supporting code passes JSLint
    for (index = 0; index < length; index += 1) {
        if (inObject(arrayLike, index)) {
            item = arrayLike[index];
            console.log('in', index, item);
        }
    }
}());
```

The above still fails JSLint as I have left the `in` example there, otherwise it passes.

http://jsfiddle.net/Xotic750/3n1a38m5/

```
Iterate based on length, no filter
length 0 a
length 1 b
length 2 null
length 3 d
length 4 undefined
length 5 undefined
length 6 f
length 7 NaN

Iterate based on length, hasOwnProperty filter
hasOwnProperty 0 a
hasOwnProperty 2 null
hasOwnProperty 3 d
hasOwnProperty 4 undefined
hasOwnProperty 6 f
hasOwnProperty 7 NaN

Iterate based on length, filter based on comparison with undefined
undefined 0 a
undefined 1 b
undefined 2 null
undefined 3 d
undefined 6 f
undefined 7 NaN

Iterate based on length, in filter
in 0 a
in 1 b
in 2 null
in 3 d
in 4 undefined
in 6 f
in 7 NaN

Iterate based on length, inObject crafted filter
in 0 a
in 1 b
in 2 null
in 3 d
in 4 undefined
in 6 f
in 7 NaN
```

So now I have used `hasOwnProperty` but look at all the supporting code that I had to produce to get the same result as when using `in`,  and comparing with `undefined` would still not be useful. 

`in` was much more succinct, very understandable and far more maintainable.

Until some proof that there is a problem with `in`, then myself and many others would take this route. I say give us some proof of a possible problem, like `eval`: it is not advisable to use but there are times when it is invaluable, even unavoidable. Let me choose to tolerate `in`, just like I choose to tolerate `eval` and stop making me jump through fiery hoops to get a pass from:

>JSLint, The JavaScript Impossible To Please Code Quality Tool

**Comment by jacksonrayhamilton** [comment]
> But no, we must not use in because it can be dangerous (when?) or because it's expensive and could lead to unexpected results (again when? I have yet to come across any).

My answer remains the same: `in` does a deep dredge through the prototype, which can lead to unexpected results.

Often when someone writes `in`, he only intends to check for an own property. But `in` looks at the prototype too:

```js
var Person = function (name) {
    this.name = name;
},
    person,
    property;
Person.prototype.doStuff = function () {};

person = new Person('Joe');

console.log('name' in person); // true
console.log('doStuff' in person); // true
console.log(Object.prototype.hasOwnProperty.call(person, 'name')); // true
console.log(Object.prototype.hasOwnProperty.call(person, 'doStuff')); // false
```

This is most apparent in the case of `for in` loops:

```js
for (property in person) {
    console.log(property);
}
// Outputs:
// name
// doStuff
```

You can avoid that by defining your methods as non-enumerable with `Object.defineProperty`:

```js
Object.defineProperty(Person.prototype, 'doStuff', {
    value: function () {}
});
```

But unfortunately, very few people take the time to define properties that way. So even if you are extra careful, if you use other people's code, and they weren't as careful, then you might run into trouble. Also, defining a property as non-enumerable still doesn't change the behavior of `in` outside of `for` loops.

Say that you wanted to use `doStuff` as a flag that indicated what you wanted to do, and you forgot (or simply did not know) that there was also a `doStuff` method on your object.

```js
if (condition) {
    person.doStuff = 'garden';
}

if ('doStuff' in person) {
    switch (person.doStuff) {
    case 'garden':
        break;
    case 'sleep':
        break;
    default:
        console.log('Invalid stuff.');
    }
}
```

Even if `condition` is falsy, `in` will still find the `doStuff` method on `person` and the code will proceed as normal.

Also, don't forget that all of the following statements return `true`:

```js
'hasOwnProperty' in {}
'isPrototypeOf' in {}
'propertyIsEnumerable' in {}
'toLocaleString' in {}
'toSource' in {}
'toString' in {}
'unwatch' in {}
'valueOf' in {}
'watch' in {}
```

Also, keep a sharp eye on the JavaScript specification and all of the browser vendors. If a new property is ever added to `Object.prototype` (in *any* implementation), then code that worked one day might stop working because you relied on `in`.

```js
var object = {};

if (condition) {
    object.isPlainObject = true;
}

if ('isPlainObject' in object) {
    // Do stuff.
}

// 5 years from now, a new ECMAScript version adds `isPlainObject` to
// `Object.prototype`. Your code might break.
```

> So you would have JSLint throw warnings against ES5 `Object.create` too?

[JSLint Alpha](http://new.jslint.com/jslint.html) disallows `this`, so yes.

**Comment by Xotic750** [comment]
Thanks for your reply and I am aware of those possibilities w.r.t. modifying `Object.prototype` without the use of ES5'sf `Object.defineProperty` and the effect on `in`, but there is nothing in JSLint that throws a warning if I modify said `prototype` without setting appropriate settings, and doing so would also break `Array#forEach` and many other methods, not just the `in` operator. The `in` operator uses the same ` [[HasProperty]]` internal method and etc. So I still see no good reason to not allow me to mark my `in`s as tolerable, I'll take the chance that another developer is not going to break the whole environment and if they do then `in` is likely to be the last of the worries.  Why not mark all methods and operators that call the ` [[HasProperty]] ` internal method etc, as unsafe? It makes no sense.

Disallows `this` or disallows `Object.create`?

**Comment by jacksonrayhamilton** [comment]
> I still see no good reason to not allow me to mark my `in`s as tolerable

I think Crockford wants to reduce the amount of options in JSLint. Many of the options in the current version only serve to reduce the quality of your code, and that contradicts the purpose of a linter. Ideally your code should pass without any "Tolerate..." options enabled. And it certainly could if you wrote it a little differently.

> Why not mark all methods and operators that call the [[HasProperty]] internal method etc, as unsafe?

Maybe they should be. Though that opens up another can of worms because even basic property access touches the prototype. You might want to ask him about that.

`in` is disallowed here because it is typically misused for the purpose of checking for own properties. `[[HasProperty]]` is probably suitable in other situations.

> Disallows `this` or disallows `Object.create`?

`this`. `Object.create` implies that you are using prototypes, which means that you probably need `this` to access data within methods. (If you were using parasitic inheritance then you wouldn't need prototypes nor `this`.) Though while disallowing `this` implies that `Object.create` isn't as useful in the context of prototypal inheritance, I forgot that `Object.create(null)` is useful for *avoiding* prototypal inheritance. So it should stick around, if not for the sole purpose of calling the function with `null`.

**Comment by Xotic750** [comment]
>Ideally your code should pass without any "Tolerate..." options enabled.

Ideally the `in` operator should be tolerated as default, it's a part of the language that is well defined, behaves just as well as any other methods/operators that rely on the same internal methods and allows creative flexibility.

>`in` is disallowed here because it is typically misused for the purpose of checking for own properties.

That's like saying we should disallow the word `what` from the English language because it is typically misused in sentences like: "words what get misused daily"

But that aside, I think you nailed it with the words

>I think Crockford wants

It's more to do with what he wants from the language rather than what the community wants. Such self imposed "strictness" leads me to move away from this tool where possible.

Don't get me wrong, I have great admiration for the works that he has achieved and brought to the language but I feel that the respect that these achievements have brought are a cause of some form of megalomania. :)

Thanks for your thoughts on the subject.

**Comment by jacksonrayhamilton** [comment]
(More thoughts on property access:)

I think oftentimes we care more about whether a property has a value than whether an object has a property. For instance, say that I want to detect the presence of a global variable. Checking

```js
if (window.cordova !== undefined) {
    // Do stuff...
}
```

would be better than

```js
if (Object.prototype.hasOwnProperty.call(window, 'cordova')) {
    // Do stuff...
}
```

because `cordova` could be a property of the `window` object, but without a value it's not of much use to me. This common situation makes the problem of "checking for the existence of a key" less of a concern.

Accessing properties in such a way that we might find them on the prototype (i.e., using `[[HasProperty]]`) shouldn't be bad. In the `forEach` algorithm, 1 step after checking for the property's existence, the property's value is then accessed. The intention here was to retrieve something, not to check for the existence of a key.

When it comes to actually checking for the existence of a key (and not its value), it would probably be better to be more specific. Specificity is generally a good thing in programming. You can use `hasOwnProperty` to specifically check an object, *or* that object's `prototype`, *or* that object's prototype's `prototype`... if that is really what you want to do. I think that even though you might be able to justify using `in` in some situations, JSLint believes the bugs avoided by a strict discipline outweigh the subtle advantages in those rare situations.

**Comment by jacksonrayhamilton** [comment]
> It's more to do with what he wants from the language rather than what the community wants.

If Crockford was right and the community was wrong (or vice-versa), I would side with whoever was right. Neither party is necessarily preferable over the other. Compare a dictatorship to a democracy: The dictator can make hard decisions -- perhaps controversial and/or *correct*, or *wrong* decisions -- immediately. A democracy makes decisions that the majority likes, but what the majority likes is not necessarily the best.

JSLint (the dictatorship) had the freedom to say that `var` statements should be restricted to one-per-function, and thus they have to be placed at the top. This helps avoid confusion about scoping, and is a good thing. But some (perhaps many) people find it aesthetically displeasing. This rule has been completely removed from JSHint because it was branded "stylistic." But the maintainers of JSHint do not realize that style and the prevention of errors are often intertwined.

JSHint has an `asi` option. Though that totally contradicts the purpose of the linter, it's what the community wants, apparently. Unfortunately, adding this feature encourages people employing the ASI "style" to continue doing so, much to everyone's detriment. JSLint will never add that feature. In this particular case I believe that JSLint is doing the community *more good* than its community-managed alternative.

JSLint won't permit trailing commas. That may or may not be the best decision (personally, I think they should be enforced). JSHint does allow them. Also, it looks like JSLint will soon allow ES6 "fat arrow" functions, though personally I think they shouldn't be used, due to their limitations, encouragement of `this`, and their potential for syntactic ambiguity. A dictator isn't perfect; he is just one man with his own biases, after all.

> Such self imposed "strictness" leads me to move away from this tool where possible.

Discipline is a good thing. For example, a responsible consumer of alcohol stays within the legal limit, lest he predispose himself to make poor decisions. He might *want* the limit on his level of intoxication to be lifted, but following a simple rule allows him to enjoy his beverages, without causing harm to himself or others.

The same goes for programming: You definitely want strict rules. It easier to have a strict set of rules that allow you to write error-free programs (even if some of those rules require a few extra seconds be spent *typing*) than it is to have a loose set of rules that allow you to write bugs (which require you to spend many minutes, or even hours, *thinking*).

**Comment by Xotic750** [comment]
I have been an avid fan of JSLint over JSHint because of it's strictness and have avidly followed the rules. But to the best of my knowledge, there is still no way to fully implement `Array#forEach` and many other shims faithfully to spec across browser without the use of `in`  (unless someone shows me another way). Reliability, repeatability and  correctness will always win over dictated linting strictness and in this situation I will continue to ignore those rules. But it means my IDE complains, I can never get a pass in JSLint and my boss will never give me the bonus I want, because of the warnings that I use the word 'what' and as per definition in the English dictionary. :)

The way that I am using `in` is correct and to specification, it not being misused for some other purpose, it is not doing any harm and in fact it is being very specific. It is the correct tool for the job at hand and I don't want to have to use a kitchen knife to unscrew a screw when I have the correct type and size of screwdriver. The fact that I can't go in and mark the warnings as ignored and impart comments at the same point in the code to explain why it is being ignored really bugs me. It also means that if I continue to be as strict when it comes to testing then my build will never complete because these warnings will cause my strict  build process to end early and never complete. This forces my hand to take another route and move away from this tool.

Ok, so I have modified my own branch to lint the way that I want. Great my IDE now stops complaining, I can use this copy in my build process without it failing. But I will still never get that bonus from the boss because I now have 3 times as many warnings in the original JSLint: the original warnings about `in` and now about unrecognized JSLint options in my comments.

I understand and thank you for you input on the subject.

**Comment by jacksonrayhamilton** [comment]
Okay, so if I'm parsing you correctly it seems that you want

> to fully implement `Array#forEach` and many other shims faithfully to spec across browser

Your premise is wrong. Don't do this. The majority of browsers in the market support ECMAScript 5, so you can just write code for that version of the language. JSLint no longer assumes ES3 rules, for instance using keywords as property names isn't even checked. If your boss still makes you write for ES3, then you shouldn't be using this linter.

You can't implement the method to spec in ES3 without `in` or without relying on the existence of a non-standard property like `__proto__`.

JSLint cannot be configured to tolerate the partial reimplementation of ECMAScript 5 in ECMAScript 3. Forking JSLint and changing it so that you pass doesn't count as passing. You should take its advice and drop support; conveniently, then you wouldn't be obligated to use `in` anymore.

In ES5, you can recursively search the prototype. If you want to pass JSLint, you can use this instead of `in`, though I doubt you will ever need to do this if you take JSLint's advice and stop using prototypes.

```js
var hasProperty = function (object, property) {
    var next = object;
    do {
        if (Object.prototype.hasOwnProperty.call(next, property)) {
            return true;
        }
        next = Object.getPrototypeOf(object);
    } while (next !== null);
    return false;
};

console.log(hasProperty({a: 1}, 'a')); // true
console.log(hasProperty({}, 'hasOwnProperty')); // true
console.log(hasProperty(Object.create(null), 'hasOwnProperty')); // false
```

**Comment by Xotic750** [comment]
If you don't need to support browsers older than IE9 and don't need to support `Object.create` then this   (or something similar) has a chance of working. Though testing this with both my ES3 and ES5 examples sent all my browsers into an infinite loop. :)

**Comment by jacksonrayhamilton** [comment]
> Though testing this with both my ES3 and ES5 examples sent all my browsers into an infinite loop. :)

I tested that snippet on Node and Chrome and it did not loop. How are you using it?

**Comment by jacksonrayhamilton** [comment]
Also, I already regret giving you that snippet. I am only humoring a foolish endeavor at this point. 

Though I feel like I am getting a bit dodgy and need to address your particular use case. You claim:

> The way that I am using in is correct and to specification, it not being misused for some other purpose, it is not doing any harm and in fact it is being very specific.

This mode of thinking is *incompatible* with JSLint's philosophy; from [http://new.jslint.com/help.html](http://new.jslint.com/help.html):

> Perfectly fine
> JSLint was designed to reject code that some would consider to be perfectly fine. The reason for this is that JSLint's purpose is to help produce programs that are free of error. That is difficult in any language and is especially hard in JavaScript. JSLint attempts to help you increase the visual distance between correct programs and incorrect programs, making the remaining errors more obvious. JSLint will give warnings about things that are not necessarily wrong in the current situation, but which have been observed to mask or obscure errors. Avoid those things when there are better options available. It is dangerous out there. JSLint is here to help.

Say that JSLint was still intended for use with ES3. Even so, despite that `in` is the only way to solve this particular problem (implementing this method *precisely* to spec), I still wouldn't use it. According to JSLint, this algorithm should not be implemented as-is. I would use `hasOwnProperty` instead of `in`. Then I would continue to protect myself against unexpected property iteration. In this case, JSLint knows better than the specification.

```js
var ArrayLike,
    arrayLike,
    iterator,
    forEach;

ArrayLike = function () {};
ArrayLike.prototype['1'] = function () {
    return 1;
};

arrayLike = new ArrayLike();
arrayLike[0] = 0;
arrayLike[2] = 2;
arrayLike.length = 3;

iterator = function (iteree, index) {
    console.log(iteree, index);
};

Array.prototype.forEach.call(arrayLike, iterator);
// Outputs:
// 0 0
// [Function] 1
// 2 2

forEach = function (array, iterator) {
    var index;
    for (index = 0; index < array.length; index += 1) {
        if (Object.prototype.hasOwnProperty.call(array, index)) {
            iterator(array[index], index);
        }
    }
};

forEach(arrayLike, iterator);
// Outputs:
// 0 0
// 2 2
```

Isn't that amazing... JSLint found an error in the ECMAScript spec! This is truly an exceptional linter.

**Comment by Xotic750** [comment]
Added your code to the two examples that I provided above and replaced the `if (index in arrayLike)` with `if (hasProperty(arrayLike, index))`.

**Comment by jacksonrayhamilton** [comment]
Fixed: [http://jsfiddle.net/rLj4e1a7/9/](http://jsfiddle.net/rLj4e1a7/9/)

**Comment by Xotic750** [comment]
I have no problem with JSLint as a tool in general and I take the advice to heart. What I do have a problem with is that it gives me advice (and the advice is poor, see the message), I check to make sure that I have not made some silly mistake and confirm that I have not. I now want to mark this as checked/confirmed and for the warning to disappear from my screen as it is now obfuscating other warnings. I don't think that is such a crime? 'be warned:listen to the advice:check the situation:choose to ignore it because confirmed usage'

The output of your code is exactly what I'd expect it to be using `[[hasOwnProperty]]` as a filter, however the spec for `Array#forEach` and others uses `[[hasProperty]]` and the only access to this is using `in`. How is that an error in the spec?  JSLint is forcing it's own idea of what the spec and language should be, not what the spec and language actually are. 

Yes, that fixes your original code. ;)

**Comment by Xotic750** [comment]
One final snippet for you to try.
```javascript
// Support required for Array# methods on IE8+ and Node 8+
(function () {
    'use strict'
    
    /**
     * Indicates if running in strict mode.
     * True if we are, otherwise false.
     *
     * @private
     * @name isStrictMode
     * @type {boolean}
     */
    var isStrictMode = (function () {
        return !this;
    }()) || false;
    
    /**
     * Checks if the supplied function suffers from the V8 strict mode bug.
     *
     * @private
     * @function hasV8StrictBug
     * @param {Function} fn
     * @returns {boolean}
     */
    function hasV8StrictBug(fn) {
        var bug = false;

        if (isStrictMode) {
            fn.call([1], function () {
                bug = typeof this === 'object';
            }, 'foo');
        }

        return bug;
    }
    
    if (!Array.prototype.forEach || hasV8StrictBug(Array.prototype.forEach)) {
        console.log('Apply a forEach shim');
        if (!Object.getPrototypeOf) {
            console.log('Need to use "in" operator for compliance');
        } else {
            console.log('Can use Object.getPrototypeOf for compliance');
        }
    } else {
        console.log('Working forEach');
    }
}());
```

**Comment by jacksonrayhamilton** [comment]
> How is that an error in the spec

In JSLint's opinion, it is an "error" to iterate over properties on the prototype, because it doesn't think that's what most programmers expect to happen. Therefore it disagrees with the way the ES5 `Array.prototype` methods are implemented.

> JSLint is forcing it's own idea of what the spec and language should be, not what the spec and language actually are.

Yes. JSLint has higher standards than the official language specification.

> But don't beat me up because I must support an environment that the owner deems dead and buried and there are no other options.

Trying to use JSLint in an ES3 environment, when JSLint requires that you work in an ES5 environment, is a contradiction.

I don't think we can have a reasonable conversation about this when your premise is contradictory. Hopefully you can convince your boss that JSLint refuses to support ES3 (and that he should take JSLint's advice and drop support for ES3), and otherwise hopefully you can convince him to use a linter that still tolerates ES3, like JSHint, and otherwise you will be miserable.

We can still have an unreasonable conversation about this in the imaginary world where it is appropriate to use JSLint for checking ES3 code. In that imaginary world, you should still follow its advice.

Don't forget:

> JSLint will give warnings about things that are not necessarily wrong in the current situation, but which have been observed to mask or obscure errors.

> things that are not necessarily wrong in the current situation

> not necessarily wrong in the current situation

> not necessarily wrong

It does not care that you have gone to extra lengths to ensure that you know what you are doing. It does. Not. Care.

And there *are* "better options" available. Don't implement the methods according to the official language specification. That is its rather extraordinary advice in this case.

I think we should pause and think about that. JSLint is so powerful that it critiques the implementation of native methods. I think that may be an indication that those methods aren't safe to use.

Imagine if we had just ignored JSLint's advice in this case and with much determination continued to implement these methods to ECMAScript's specification? Years down the road we could be iterating over a method called "1" in a holey array, and it wouldn't be until that frustrating night of debugging that we finally realized we had been tricked.

**Comment by Xotic750** [comment]
Ok, if we are to interpret it in that way then what we are saying is that we should be looking at the specs of all the built-in prototype methods that we us and if they use ``[[hasProperty]]` then we shouldn't use them and instead we should construct our own, in a similar style, but using ```[[hasOwnProperty]]`` instead. So looking at the majority of `Array#` methods, so for example `Array#slice` should not be used (just one of the older ES3, there are more), then looking at ES5 we should pretty much never use any of the newer `Array#` methods and then looking forward to ES6 we have the same situation with `Array#` and things like `from` and `of` and `contains` and the `find`s. And when we write our own which use ``[[hasOwnProperty]]`` don't replace the ones on the prototype, instead make them stand-alone functions and instead of using ``this`` for the object have them take an argument in which you supply the object as the first argument. And all the callback/iterator functions that have been used by the likes of `Array#forEach` should be re-written and and where we have used `call` and `apply` with a `this` value then they need to be changed to have their first argument set to `null` as we will now pass everything by argument and not `this`- We'll keep `Object.create` but only for use with `null` so we can create out own empty object without a `prototype` and we will not use the `prototype` object and feature of the language. I've got an idea, Crockford should stop wasting his time developing JSLint and write a new language instead.

**Comment by Xotic750** [comment]
No need for the option now, this should keep the boss happy with an unmodified JSLint. :)
```javascript
(function () {
    'use strict';
    /*jslint devel: true */
    /*globals Array */
    /*properties
        '1', call, constructor, forEach, hasOwnProperty, length, log, prototype
    */

    function hasProperty(object, prop) {
        /*jslint unparam: true, evil: true */
        return eval('prop in object');
    }

    var ArrayLike,
        arrayLike,
        iterator,
        forEach;

    ArrayLike = function () { return; };
    ArrayLike.prototype['1'] = function () {
        return 1;
    };

    arrayLike = new ArrayLike();
    arrayLike[0] = 0;
    arrayLike[2] = 2;
    arrayLike.length = 3;

    iterator = function (iteree, index) {
        console.log(iteree, index);
    };

    Array.prototype.forEach.call(arrayLike, iterator);

    forEach = function (array, iterator) {
        var index;

        for (index = 0; index < array.length; index += 1) {
            if (hasProperty(array, index)) {
                iterator(array[index], index);
            }
        }
    };

    forEach(arrayLike, iterator);
}());
```

**Comment by jacksonrayhamilton** [comment]
For your second-to-last comment: Yes. It is a rather extraordinary request. Principally-speaking it might be a better approach to do that, though realistically I think the chance of "numerical" methods appearing on prototypes is pretty slim. IMO it is probably still safe to use methods which invoke `[[HasProperty]]` for the purpose of checking array indices, though as noted previously JSLint doesn't like to be selectively tolerant.

Maybe it is right, and we are being lazy by using these "risky" implementations of aggregate operations. I would be disappointed if it turned out to be right, but ignorance is bliss, after all.

Or, maybe it is being uncompromisingly strict and we are being smart by not going to all that trouble for arguably very little payback. I can't say for certain at this time.

For your last comment: Talk to your boss.

**Comment by Xotic750** [comment]
Haha. Persuading the boss to tolerate a warning is like persuading  Crockford to add an option to tolerate `in.` Result in both cases: misuse of the language. :D

**Comment by jacksonrayhamilton** [comment]
No. Tell him that JSLint does not support ES3 and thus is inadequate (actually, risky) to use for ES3 code. Show him the commits that remove support for ES3 checks, like reserved words for keywords et al. If he is a reasonable person, either he will admit that JSLint is right and he should move on to ES5, or he will realize the business risk in using the wrong tool for the job and switch to JSHint. If he is unreasonable then I am sorry. Please at least reach out to him.

**Comment by Xotic750** [comment]
Wow! It appears that Mr. Crockford has now blocked me from forking or participating in any projects that are owned by him on GitHub! Have emailed him to see if this is intentional or not. :/

**Comment by Xotic750** [comment]
We have moved to jsHint! :) unfortunately my IDE is still using jsLint and so need the patched version of my fork so that I can get rid of the warnings on my screen, but on the build side of things all is much happier. On a further note, no response or unblocking from Mr.Crockford!

**Comment by jacksonrayhamilton** [comment]
Good to hear. JSHint is the right tool for working on ES3 code.

**Pull request closed without merging**
